image: node:18

pages:
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build
  only:
    - main
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
